application: go-read
version: c
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: static/favicon.png
  upload: static/favicon.png

- url: /static
  static_dir: static

- url: /login/google
  login: required
  script: _go_app

- url: /user/.*
  login: required
  script: _go_app

- url: /task/.*
  login: admin
  script: _go_app

- url: /admin/.*
  login: admin
  script: _go_app

- url: /.*
  script: _go_app
